package com.eshqol.sigma

import android.app.Activity
import android.util.Log
import android.view.Gravity
import android.view.View
import android.widget.FrameLayout
import android.widget.ImageView
import android.widget.Toast
import com.google.android.material.snackbar.Snackbar


fun String.log(tag: String = "tag123"){
    Log.i(tag, "log: $this")
}


fun String.show(activity: Activity){
    Toast.makeText(activity, this, Toast.LENGTH_SHORT).show()
}

fun String.snack(activity: Activity, duration: Int = Snackbar.LENGTH_SHORT, top: Boolean = false){
    val parentLayout = activity.findViewById<View>(android.R.id.content)

    if (!top)
        Snackbar.make(parentLayout, this, duration).show()
    else{
        val snack = Snackbar.make(parentLayout, this, duration)
        val view = snack.view
        val params = view.layoutParams as FrameLayout.LayoutParams
        params.gravity = Gravity.TOP
        view.layoutParams = params
        snack.show()
    }
}


fun ImageView.setProfileImage(proId: String) {
    when (proId){
        "1" -> setImageResource(R.drawable.p1)
        "2" -> setImageResource(R.drawable.p2)
        "3" -> setImageResource(R.drawable.p3)
        "4" -> setImageResource(R.drawable.p4)
        "5" -> setImageResource(R.drawable.p5)
        "6" -> setImageResource(R.drawable.p6)
        "7" -> setImageResource(R.drawable.p7)
        "8" -> setImageResource(R.drawable.p8)
        "9" -> setImageResource(R.drawable.p9)
        "10" -> setImageResource(R.drawable.p10)
        "11" -> setImageResource(R.drawable.p111)
        "12" -> setImageResource(R.drawable.p12)
        "13" -> setImageResource(R.drawable.p13)
        "14" -> setImageResource(R.drawable.p14)
        "15" -> setImageResource(R.drawable.p15)
        "16" -> setImageResource(R.drawable.p16)
        "17" -> setImageResource(R.drawable.p17)
        "18" -> setImageResource(R.drawable.p18)
        "19" -> setImageResource(R.drawable.p19)
    }
}



fun ImageView.setFlag(flagId: String){
    when (flagId.lowercase()){
        "ao" -> setImageResource(R.drawable.angola)
        "ag" -> setImageResource(R.drawable.antigua_and_barbuda)
        "ar" -> setImageResource(R.drawable.argentina)
        "am" -> setImageResource(R.drawable.armenia)
        "aw" -> setImageResource(R.drawable.aruba)
        "au" -> setImageResource(R.drawable.australia)
        "at" -> setImageResource(R.drawable.austria)
        "az" -> setImageResource(R.drawable.azerbaijan)
        "bs" -> setImageResource(R.drawable.bahamas)
        "bh" -> setImageResource(R.drawable.bahrain)
        "bd" -> setImageResource(R.drawable.bangladesh)
        "bb" -> setImageResource(R.drawable.barbados)
        "by" -> setImageResource(R.drawable.belarus)
        "be" -> setImageResource(R.drawable.belgium)
        "bz" -> setImageResource(R.drawable.belize)
        "bj" -> setImageResource(R.drawable.benin)
        "bt" -> setImageResource(R.drawable.bhutan)
        "ba" -> setImageResource(R.drawable.bosnia_and_herzegovina)
        "bw" -> setImageResource(R.drawable.botswana)
        "br" -> setImageResource(R.drawable.brazil)
        "bg" -> setImageResource(R.drawable.bulgaria)
        "bf" -> setImageResource(R.drawable.burkina_faso)
        "bi" -> setImageResource(R.drawable.burundi)
        "kh" -> setImageResource(R.drawable.cambodia)
        "cm" -> setImageResource(R.drawable.cameroon)
        "ca" -> setImageResource(R.drawable.canada)
        "cf" -> setImageResource(R.drawable.central_african_republic)
        "td" -> setImageResource(R.drawable.chad)
        "cl" -> setImageResource(R.drawable.chile)
        "cn" -> setImageResource(R.drawable.china)
        "co" -> setImageResource(R.drawable.colombia)
        "km" -> setImageResource(R.drawable.comoros)
        "cr" -> setImageResource(R.drawable.costa_rica)
        "hr" -> setImageResource(R.drawable.croatia)
        "cu" -> setImageResource(R.drawable.cuba)
        "cy" -> setImageResource(R.drawable.cyprus)
        "dk" -> setImageResource(R.drawable.denmark)
        "dj" -> setImageResource(R.drawable.djibouti)
        "dm" -> setImageResource(R.drawable.dominica)
        "do" -> setImageResource(R.drawable.dominican_republic)
        "ec" -> setImageResource(R.drawable.ecuador)
        "eg" -> setImageResource(R.drawable.egypt)
        "sv" -> setImageResource(R.drawable.el_salvador)
        "gq" -> setImageResource(R.drawable.equatorial_guinea)
        "er" -> setImageResource(R.drawable.eritrea)
        "ee" -> setImageResource(R.drawable.estonia)
        "et" -> setImageResource(R.drawable.ethiopia)
        "fo" -> setImageResource(R.drawable.faroe_islands)
        "fj" -> setImageResource(R.drawable.fiji)
        "fi" -> setImageResource(R.drawable.finland)
        "fr" -> setImageResource(R.drawable.france)
        "ga" -> setImageResource(R.drawable.gabon)
        "gm" -> setImageResource(R.drawable.gambia)
        "ge" -> setImageResource(R.drawable.georgia)
        "de" -> setImageResource(R.drawable.germany)
        "gh" -> setImageResource(R.drawable.ghana)
        "gr" -> setImageResource(R.drawable.greece)
        "gl" -> setImageResource(R.drawable.greenland)
        "gd" -> setImageResource(R.drawable.grenada)
        "gp" -> setImageResource(R.drawable.guadeloupe)
        "gu" -> setImageResource(R.drawable.guam)
        "gt" -> setImageResource(R.drawable.guatemala)
        "gn" -> setImageResource(R.drawable.guinea)
        "gy" -> setImageResource(R.drawable.guyana)
        "ht" -> setImageResource(R.drawable.haiti)
        "hn" -> setImageResource(R.drawable.honduras)
        "hk" -> setImageResource(R.drawable.hongkong)
        "hu" -> setImageResource(R.drawable.hungary)
        "is" -> setImageResource(R.drawable.iceland)
        "in" -> setImageResource(R.drawable.india)
        "id" -> setImageResource(R.drawable.indonesia)
        "ir" -> setImageResource(R.drawable.iran)
        "iq" -> setImageResource(R.drawable.iraq)
        "ie" -> setImageResource(R.drawable.ireland)
        "il" -> setImageResource(R.drawable.israel)
        "it" -> setImageResource(R.drawable.italy)
        "jm" -> setImageResource(R.drawable.jamaica)
        "jp" -> setImageResource(R.drawable.japan)
        "jo" -> setImageResource(R.drawable.jordan)
        "kz" -> setImageResource(R.drawable.kazakhstan)
        "ke" -> setImageResource(R.drawable.kenya)
        "ki" -> setImageResource(R.drawable.kiribati)
        "kr" -> setImageResource(R.drawable.south_korea)
        "kw" -> setImageResource(R.drawable.kuwait)
        "kg" -> setImageResource(R.drawable.kyrgyzstan)
        "lv" -> setImageResource(R.drawable.latvia)
        "lb" -> setImageResource(R.drawable.lebanon)
        "ls" -> setImageResource(R.drawable.lesotho)
        "lr" -> setImageResource(R.drawable.liberia)
        "ly" -> setImageResource(R.drawable.libya)
        "li" -> setImageResource(R.drawable.liechtenstein)
        "lt" -> setImageResource(R.drawable.lithuania)
        "lu" -> setImageResource(R.drawable.luxembourg)
        "mg" -> setImageResource(R.drawable.madagascar)
        "mw" -> setImageResource(R.drawable.malawi)
        "my" -> setImageResource(R.drawable.malaysia)
        "mv" -> setImageResource(R.drawable.maldives)
        "ml" -> setImageResource(R.drawable.mali)
        "mt" -> setImageResource(R.drawable.malta)
        "mh" -> setImageResource(R.drawable.marshall_islands)
        "mr" -> setImageResource(R.drawable.mauritania)
        "mu" -> setImageResource(R.drawable.mauritius)
        "mx" -> setImageResource(R.drawable.mexico)
        "fm" -> setImageResource(R.drawable.micronesia)
        "md" -> setImageResource(R.drawable.moldova)
        "mc" -> setImageResource(R.drawable.monaco)
        "mn" -> setImageResource(R.drawable.mongolia)
        "me" -> setImageResource(R.drawable.montenegro)
        "ma" -> setImageResource(R.drawable.morocco)
        "mz" -> setImageResource(R.drawable.mozambique)
        "mm" -> setImageResource(R.drawable.myanmar)
        "na" -> setImageResource(R.drawable.namibia)
        "nr" -> setImageResource(R.drawable.nauru)
        "np" -> setImageResource(R.drawable.nepal)
        "nl" -> setImageResource(R.drawable.netherlands)
        "nc" -> setImageResource(R.drawable.new_caledonia)
        "nz" -> setImageResource(R.drawable.new_zealand)
        "ni" -> setImageResource(R.drawable.nicaragua)
        "ne" -> setImageResource(R.drawable.niger)
        "ng" -> setImageResource(R.drawable.nigeria)
        "nu" -> setImageResource(R.drawable.niue)
        "mp" -> setImageResource(R.drawable.northern_mariana_islands)
        "no" -> setImageResource(R.drawable.norway)
        "om" -> setImageResource(R.drawable.oman)
        "pk" -> setImageResource(R.drawable.pakistan)
        "pw" -> setImageResource(R.drawable.palau)
        "ps" -> setImageResource(R.drawable.palestine)
        "pa" -> setImageResource(R.drawable.panama)
        "pg" -> setImageResource(R.drawable.papua_new_guinea)
        "py" -> setImageResource(R.drawable.paraguay)
        "pe" -> setImageResource(R.drawable.peru)
        "ph" -> setImageResource(R.drawable.philippines)
        "pl" -> setImageResource(R.drawable.poland)
        "pt" -> setImageResource(R.drawable.portugal)
        "pr" -> setImageResource(R.drawable.puerto_rico)
        "qa" -> setImageResource(R.drawable.qatar)
        "mk" -> setImageResource(R.drawable.macedonia)
        "ro" -> setImageResource(R.drawable.romania)
        "ru" -> setImageResource(R.drawable.russia)
        "rw" -> setImageResource(R.drawable.rwanda)
        "kn" -> setImageResource(R.drawable.saint_kitts_and_nevis)
        "lc" -> setImageResource(R.drawable.saint_lucia)
        "vc" -> setImageResource(R.drawable.saint_vincent_and_the_grenadines)
        "ws" -> setImageResource(R.drawable.samoa)
        "sm" -> setImageResource(R.drawable.san_marino)
        "st" -> setImageResource(R.drawable.sao_tome_and_principe)
        "sa" -> setImageResource(R.drawable.saudi_arabia)
        "sn" -> setImageResource(R.drawable.senegal)
        "rs" -> setImageResource(R.drawable.serbia)
        "sc" -> setImageResource(R.drawable.seychelles)
        "sl" -> setImageResource(R.drawable.sierra_leone)
        "sg" -> setImageResource(R.drawable.singapore)
        "sk" -> setImageResource(R.drawable.slovakia)
        "si" -> setImageResource(R.drawable.slovenia)
        "sb" -> setImageResource(R.drawable.solomon_islands)
        "so" -> setImageResource(R.drawable.somalia)
        "za" -> setImageResource(R.drawable.south_africa)
        "ss" -> setImageResource(R.drawable.south_sudan)
        "es" -> setImageResource(R.drawable.spain)
        "lk" -> setImageResource(R.drawable.sri_lanka)
        "sd" -> setImageResource(R.drawable.sudan)
        "sr" -> setImageResource(R.drawable.suriname)
        "se" -> setImageResource(R.drawable.sweden)
        "ch" -> setImageResource(R.drawable.switzerland)
        "sy" -> setImageResource(R.drawable.syria)
        "tw" -> setImageResource(R.drawable.taiwan)
        "tj" -> setImageResource(R.drawable.tajikistan)
        "tz" -> setImageResource(R.drawable.tanzania)
        "th" -> setImageResource(R.drawable.thailand)
        "tl" -> setImageResource(R.drawable.east_timor)
        "tg" -> setImageResource(R.drawable.togo)
        "to" -> setImageResource(R.drawable.tonga)
        "tt" -> setImageResource(R.drawable.trinidad_and_tobago)
        "tn" -> setImageResource(R.drawable.tunisia)
        "tr" -> setImageResource(R.drawable.turkey)
        "tm" -> setImageResource(R.drawable.turkmenistan)
        "tv" -> setImageResource(R.drawable.tuvalu)
        "ug" -> setImageResource(R.drawable.uganda)
        "ua" -> setImageResource(R.drawable.ukraine)
        "ae" -> setImageResource(R.drawable.united_arab_emirates)
        "gb" -> setImageResource(R.drawable.united_kingdom)
        "um" -> setImageResource(R.drawable.united_states_of_america)
        "us" -> setImageResource(R.drawable.united_states_of_america)
        "uy" -> setImageResource(R.drawable.uruguay)
        "uz" -> setImageResource(R.drawable.uzbekistan)
        "vu" -> setImageResource(R.drawable.vanuatu)
        "ve" -> setImageResource(R.drawable.venezuela)
        "vn" -> setImageResource(R.drawable.vietnam)
        "ye" -> setImageResource(R.drawable.yemen)
        "zm" -> setImageResource(R.drawable.zambia)
        "zw" -> setImageResource(R.drawable.zimbabwe)
        "uk" -> setImageResource(R.drawable.united_kingdom)
        else -> setImageResource(R.drawable.unknow_country)
    }

}



